version: '3.8'

services:
  api-gateway:
    image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/api-gateway:latest"
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://localhost:6379
      - RABBITMQ_URL=amqp://localhost:5672
    depends_on:
      - redis
      - rabbitmq
      - mongo

  identity-service:
    image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/identity-service:latest"
    container_name: identity-service
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://localhost:6379
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo
      - redis

  post-service:
    image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/post-service:latest"
    container_name: post-service
    ports:
      - "3002:3002"
    environment:
      - REDIS_URL=redis://localhost:6379
      - RABBITMQ_URL=amqp://localhost:5672
    depends_on:
      - redis
      - rabbitmq

  media-service:
    image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/media-service:latest"
    container_name: post-service
    ports:
      - "3003:3003"
    environment:
      - REDIS_URL=redis://localhost:6379
      - RABBITMQ_URL=amqp://localhost:5672
    depends_on:
      - redis
      - rabbitmq

  search-service:
    image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/search-service:latest"
    container_name: post-service
    ports:
      - "3004:3004"
    environment:
      - REDIS_URL=redis://localhost:6379
      - RABBITMQ_URL=amqp://localhost:5672
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: "mongo:latest"
    container_name: mongo
    ports:
      - "27017:27017"
